default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: arua_backend_development
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5433) %>
  username: <%= ENV.fetch("DB_USERNAME", "arua") %>
  password: <%= ENV.fetch("DB_PASSWORD", "arua_dev") %>

test:
  <<: *default
  database: arua_backend_test

production:
  <<: *default
  database: arua_backend_production
  username: arua_backend
  password: <%= ENV["ARUA_BACKEND_DATABASE_PASSWORD"] %>
